import { sql, type Transaction } from 'kysely';
import readline from 'readline';
import { z } from 'zod';

import { db } from '../shared/db';
import { IS_PRODUCTION } from '../shared/env';
import { type DB } from '../shared/types';
import { migrate } from '../use-cases/migrate';
import { truncate } from '../use-cases/truncate';

if (IS_PRODUCTION) {
  throw new Error('Cannot seed database in non-development environment.');
}

async function main() {
  try {
    await setEmailFromCommandLine();
    console.log('(1/4) Email looks good. ✅');

    await migrate({ db });
    console.log('(2/4) Ran migrations and initialized tables. ✅');

    await db.transaction().execute(async (trx) => {
      await truncate(trx);
      await seed(trx);
    });

    console.log('(3/4) Wiped all data. ✅');
    console.log('(4/4) Seeded the database. ✅');
  } catch (e) {
    console.error(e);
    process.exit(1);
  } finally {
    await db.destroy();
  }
}

let email = '';

async function setEmailFromCommandLine() {
  const answer = await question(
    'In order to log into the Member Profile and Admin Dashboard, you will need both a member record and an admin record. Please provide an email so we can create those for you.\n' +
      'Email: '
  );

  const result = z
    .string()
    .trim()
    .min(1)
    .email()
    .transform((value) => {
      return value.toLowerCase();
    })
    .safeParse(answer);

  if (!result.success) {
    throw new Error('The email you provided was invalid.');
  }

  email = result.data;
}

async function question(prompt: string) {
  const cli = readline.createInterface({
    input: process.stdin,
    output: process.stdout,
  });

  return new Promise<string>((resolve) => {
    cli.question(prompt, (input) => {
      resolve(input);
      cli.close();
    });
  });
}

let counter = 0;

function id() {
  counter++;

  return counter.toString();
}

async function seed(trx: Transaction<DB>) {
  const schoolId1 = id();
  const schoolId2 = id();
  const schoolId3 = id();

  await trx
    .insertInto('schools')
    .values([
      {
        addressCity: 'Pittsburgh',
        addressState: 'PA',
        addressZip: '15213',
        id: schoolId1,
        name: 'Carnegie Mellon University',
      },
      {
        addressCity: 'Ithaca',
        addressState: 'NY',
        addressZip: '14850',
        id: schoolId2,
        name: 'Cornell University',
      },
      {
        addressCity: 'Austin',
        addressState: 'TX',
        addressZip: '78712',
        id: schoolId3,
        name: 'University of Texas at Austin',
      },
      {
        addressCity: 'Washington',
        addressState: 'D.C.',
        addressZip: '20059',
        id: id(),
        name: 'Howard University',
      },
      {
        addressCity: 'Kennesaw',
        addressState: 'GA',
        addressZip: '30144',
        id: id(),
        name: 'Kennesaw State University',
      },
      {
        addressCity: 'Berkeley',
        addressState: 'CA',
        addressZip: '94720',
        id: id(),
        name: 'University of California, Berkeley',
      },
    ])
    .execute();

  await trx
    .insertInto('admins')
    .values([
      {
        email,
        id: id(),
        firstName: 'First',
        lastName: 'Last',
        role: 'owner',
      },
    ])
    .execute();

  const memberId1 = id();
  const memberId2 = id();
  const memberId3 = id();

  const memberEmail1 = email;
  const memberEmail2 = 'savannah@james.com';
  const memberEmail3 = 'lebron@james.com';

  await trx
    .insertInto('studentEmails')
    .values([
      { email: memberEmail1 },
      { email: memberEmail2 },
      { email: memberEmail3 },
    ])
    .execute();

  await trx
    .insertInto('students')
    .values([
      {
        acceptedAt: new Date(),
        currentLocation: 'New York, NY',
        currentLocationCoordinates: sql`point(-73.935242, 40.73061)`,
        educationLevel: 'undergraduate',
        email: memberEmail1,
        firstName: 'First',
        gender: '',
        graduationYear: new Date().getFullYear().toString(),
        id: memberId1,
        joinedMemberDirectoryAt: new Date(),
        lastName: 'Last',
        major: 'computer_science',
        otherDemographics: [],
        race: [],
        schoolId: schoolId1,
      },
      {
        acceptedAt: new Date(),
        currentLocation: 'New York, NY',
        currentLocationCoordinates: sql`point(-73.935242, 40.73061)`,
        educationLevel: 'undergraduate',
        email: memberEmail2,
        firstName: 'LeBron',
        gender: '',
        graduationYear: new Date().getFullYear().toString(),
        id: memberId2,
        lastName: 'James',
        joinedMemberDirectoryAt: new Date(),
        major: 'computer_science',
        otherDemographics: [],
        race: [],
        schoolId: schoolId2,
      },
      {
        acceptedAt: new Date(),
        currentLocation: 'New York, NY',
        currentLocationCoordinates: sql`point(-73.935242, 40.73061)`,
        educationLevel: 'undergraduate',
        email: memberEmail3,
        firstName: 'Savannah',
        gender: '',
        graduationYear: new Date().getFullYear().toString(),
        id: memberId3,
        lastName: 'James',
        joinedMemberDirectoryAt: new Date(),
        major: 'computer_science',
        otherDemographics: [],
        race: [],
        schoolId: schoolId2,
      },
    ])
    .execute();

  await trx
    .updateTable('studentEmails')
    .set({ studentId: memberId1 })
    .where('email', '=', memberEmail1)
    .execute();

  await trx
    .updateTable('studentEmails')
    .set({ studentId: memberId2 })
    .where('email', '=', memberEmail2)
    .execute();

  await trx
    .updateTable('studentEmails')
    .set({ studentId: memberId3 })
    .where('email', '=', memberEmail3)
    .execute();

  await trx
    .insertInto('applications')
    .values([
      {
        id: id(),
        email: 'student1@cornell.edu',
        contribution: 'Working on Oyster!',
        educationLevel: 'undergraduate',
        gender: '',
        goals: '',
        graduationYear: 2026,
        firstName: 'Big',
        lastName: 'Red',
        linkedInUrl: 'https://www.linkedin.com/',
        major: 'computer_science',
        otherDemographics: [],
        race: [],
        schoolId: schoolId2,
        status: 'pending',
      },
      {
        id: id(),
        email: 'student2@utexas.edu',
        contribution: 'Working on Oyster!',
        educationLevel: 'Bootcamp',
        gender: '',
        goals: '',
        graduationYear: 2024,
        firstName: 'Bevo',
        lastName: 'Longhorn',
        linkedInUrl: 'https://www.linkedin.com/',
        major: 'information_science',
        otherDemographics: [''],
        race: [''],
        schoolId: schoolId3,
        status: 'pending',
      },
    ])
    .execute();

  // Companies

  const companyId1 = id();
  const companyId2 = id();
  const companyId3 = id();
  const companyId4 = id();
  const companyId5 = id();

  await trx
    .insertInto('companies')
    .values([
      {
        createdAt: new Date(),
        crunchbaseId: '172a34b4-9edd-b0ae-c768-cbfa8e1ab52c',
        description:
          'Adobe is a software company that provides its users with digital marketing and media solutions.',
        domain: 'adobe.com',
        id: companyId1,
        imageUrl:
          'https://images.crunchbase.com/image/upload/t_cb-default-original/qnbpcajqvlw8bkul1tru',
        leetcodeSlug: 'adobe',
        levelsFyiSlug: 'adobe',
        name: 'Adobe',
        stockSymbol: 'NASDAQ:ADBE',
      },
      {
        createdAt: new Date(),
        crunchbaseId: '05554f65-6aa9-4dd1-6271-8ce2d60f10c4',
        description:
          'Amazon is an e-commerce website for consumers, sellers, and content creators.',
        domain: 'amazon.com',
        id: companyId2,
        imageUrl:
          'https://images.crunchbase.com/image/upload/t_cb-default-original/mwsza2s38epb8olssp3j',
        leetcodeSlug: 'amazon',
        levelsFyiSlug: 'amazon',
        name: 'Amazon',
        stockSymbol: 'NASDAQ:AMZN',
      },
      {
        createdAt: new Date(),
        crunchbaseId: '6acfa7da-1dbd-936e-d985-cf07a1b27711',
        description:
          'Google is a multinational corporation that specializes in Internet-related services and products.',
        domain: 'google.com',
        id: companyId3,
        imageUrl:
          'https://images.crunchbase.com/image/upload/t_cb-default-original/fa8nmvofinznny6rkwvf',
        leetcodeSlug: 'google',
        levelsFyiSlug: 'google',
        name: 'Google',
        stockSymbol: 'NASDAQ:GOOG',
      },
      {
        createdAt: new Date(),
        crunchbaseId: 'df662812-7f97-0b43-9d3e-12f64f504fbb',
        description:
          'Meta is a social technology company that enables people to connect, find communities, and grow businesses.',
        domain: 'meta.com',
        id: companyId4,
        imageUrl:
          'https://images.crunchbase.com/image/upload/t_cb-default-original/whm4ed1rrc8skbdi3biv',
        leetcodeSlug: 'facebook',
        levelsFyiSlug: 'facebook',
        name: 'Meta',
        stockSymbol: 'NASDAQ:META',
      },
      {
        createdAt: new Date(),
        crunchbaseId: 'fd80725f-53fc-7009-9878-aeecf1e9ffbb',
        description:
          'Microsoft is a software corporation that develops, manufactures, licenses, supports, and sells a range of software products and services.',
        domain: 'microsoft.com',
        id: companyId5,
        imageUrl:
          'https://images.crunchbase.com/image/upload/t_cb-default-original/v1501613147',
        leetcodeSlug: 'microsoft',
        levelsFyiSlug: 'microsoft',
        name: 'Microsoft',
        stockSymbol: 'NASDAQ:MSFT',
      },
    ])
    .execute();

  // Opportunities

  const opportunityId1 = id();
  const opportunityId2 = id();
  const opportunityId3 = id();
  const opportunityId4 = id();
  const opportunityId5 = id();

  await trx
    .insertInto('opportunities')
    .values([
      {
        companyId: companyId1,
        createdAt: new Date(),
        description: `Join Adobe Experience Cloud as a web front-end engineer on a mobile experience team. Develop UI components using JavaScript, TypeScript, and React. Collaborate with engineers, product managers, and designers. Requires 1-3 years of experience. Salary range: $93,200 - $170,600 annually, varies by location.`,
        expiresAt: new Date(Date.now() + 1000 * 60 * 60 * 24 * 30),
        id: opportunityId1,
        lastExpirationCheck: undefined,
        link: 'https://careers.adobe.com/us/en/job/R152882/Software-Development-Engineer-Front-end',
        postedBy: memberId1,
        refinedAt: new Date(),
        slackChannelId: undefined,
        slackMessageId: undefined,
        title: 'Software Development Engineer, Frontend',
      },
      {
        companyId: companyId2,
        createdAt: new Date(),
        description: `12-week summer internship at Amazon Web Services (AWS) for students pursuing a Bachelor's or Master's in Engineering. Work on data center design, troubleshooting, and support operational issues. Gain experience in power systems, HVAC, and innovative solutions for AWS data centers.`,
        expiresAt: new Date(Date.now() + 1000 * 60 * 60 * 24 * 30),
        id: opportunityId2,
        lastExpirationCheck: undefined,
        link: 'https://amazon.jobs/en/jobs/2847022/data-center-infrastructure-engineer-intern',
        postedBy: memberId2,
        refinedAt: new Date(),
        slackChannelId: undefined,
        slackMessageId: undefined,
        title: 'Data Center Infrastructure Engineer Intern',
      },
      {
        companyId: companyId3,
        createdAt: new Date(),
        description: `Google seeks a UX Designer for their Searchbox and Suggest team. The role involves creating intuitive user experiences, from concept to execution, for consumer-facing digital products. Candidates should have a Bachelor's degree in Design or related field, 1 year of UX design experience, and proficiency in design tools.`,
        expiresAt: new Date(Date.now() + 1000 * 60 * 60 * 24 * 30),
        id: opportunityId3,
        lastExpirationCheck: undefined,
        link: 'https://www.google.com/about/careers/applications/jobs/results/109175665332232902-user-experience-designer-early-career-search',
        postedBy: memberId3,
        refinedAt: new Date(),
        slackChannelId: undefined,
        slackMessageId: undefined,
        title: 'User Experience Designer, Early Career, Search',
      },
      {
        companyId: companyId4,
        createdAt: new Date(),
        description: `Shape the future of Meta's products by applying technical skills and analytical mindset to one of the world's richest data sets. Collaborate with cross-functional teams, influence product strategy, and solve product development challenges. Opportunity for recent graduates with experience in data analysis and programming.`,
        expiresAt: new Date(Date.now() + 1000 * 60 * 60 * 24 * 30),
        id: opportunityId4,
        lastExpirationCheck: undefined,
        link: 'https://www.metacareers.com/jobs/1132866414844525/',
        postedBy: memberId1,
        refinedAt: new Date(),
        slackChannelId: undefined,
        slackMessageId: undefined,
        title: 'Data Scientist, Product Analytics',
      },
      {
        companyId: companyId5,
        createdAt: new Date(),
        description: `Microsoft offers 55 scholarships totaling $150,000 for Black and African American high school seniors planning to pursue technology-related degrees. Awards range from $2,500 to $5,000, with some renewable. Applicants must demonstrate leadership, financial need, and a passion for technology.`,
        expiresAt: new Date(Date.now() + 1000 * 60 * 60 * 24 * 30),
        id: opportunityId5,
        lastExpirationCheck: undefined,
        link: 'https://www.microsoft.com/en-us/diversity/programs/bam-scholarship?oneroute=true',
        postedBy: memberId2,
        refinedAt: new Date(),
        slackChannelId: undefined,
        slackMessageId: undefined,
        title: 'Black at Microsoft (BAM) Scholarships',
      },
    ])
    .execute();

  const aiTagId = id();
  const earlyCareerTagId = id();
  const hardwareTagId = id();
  const internshipTagId = id();
  const pmTagId = id();
  const quantTagId = id();
  const scholarshipTagId = id();
  const sweTagId = id();
  const uxTagId = id();

  await trx
    .insertInto('opportunityTags')
    .values([
      { color: 'amber-100', id: aiTagId, name: 'AI/ML' },
      { color: 'purple-100', id: earlyCareerTagId, name: 'Early Career' },
      { color: 'orange-100', id: hardwareTagId, name: 'Hardware' },
      { color: 'blue-100', id: internshipTagId, name: 'Internship' },
      { color: 'red-100', id: pmTagId, name: 'PM' },
      { color: 'cyan-100', id: quantTagId, name: 'Quantitative' },
      { color: 'amber-100', id: scholarshipTagId, name: 'Scholarship' },
      { color: 'lime-100', id: sweTagId, name: 'SWE' },
      { color: 'orange-100', id: uxTagId, name: 'UI/UX Design' },
    ])
    .execute();

  await trx
    .insertInto('opportunityTagAssociations')
    .values([
      { opportunityId: opportunityId1, tagId: earlyCareerTagId },
      { opportunityId: opportunityId1, tagId: sweTagId },
      { opportunityId: opportunityId2, tagId: internshipTagId },
      { opportunityId: opportunityId2, tagId: hardwareTagId },
      { opportunityId: opportunityId3, tagId: earlyCareerTagId },
      { opportunityId: opportunityId3, tagId: uxTagId },
      { opportunityId: opportunityId4, tagId: aiTagId },
      { opportunityId: opportunityId4, tagId: earlyCareerTagId },
      { opportunityId: opportunityId5, tagId: scholarshipTagId },
    ])
    .execute();

  // Resources

  const resourceId1 = id();
  const resourceId2 = id();
  const resourceId3 = id();

  await trx
    .insertInto('resources')
    .values([
      {
        description: `Here's a curated list of tagged LeetCode questions, all for free without the need for LeetCode Premium.`,
        id: resourceId1,
        link: 'https://github.com/krishnadey30/LeetCode-Questions-CompanyWise',
        postedAt: new Date(),
        postedBy: memberId1,
        title: 'Tagged Leetcode Questions',
        type: 'url',
      },
      {
        description: `A session from our May '23 Fam Friday: Do You, held on 5/26/23. Hosted by Bloomberg.`,
        id: resourceId2,
        link: 'https://www.youtube.com/watch?v=mz2xcQ6KjF0',
        postedAt: new Date(),
        postedBy: memberId2,
        title: 'How to Succeed in Your Internship',
        type: 'url',
      },
      {
        description: `CodeSignal's course paths offer structured learning in coding, covering topics like data structures, algorithms, and web development for all skill levels.`,
        id: resourceId3,
        link: 'https://codesignal.com/learn',
        postedAt: new Date(),
        postedBy: memberId3,
        title: 'CodeSignal Learn',
        type: 'url',
      },
    ])
    .execute();

  const academicTagId = id();
  const careerAdviceTagId = id();
  const interviewPrepTagId = id();
  const learningTagId = id();
  const videoTagId = id();

  await trx
    .insertInto('tags')
    .values([
      { id: academicTagId, name: 'Academic' },
      { id: careerAdviceTagId, name: 'Career Advice' },
      { id: interviewPrepTagId, name: 'Interview Prep' },
      { id: learningTagId, name: 'Learning' },
      { id: videoTagId, name: 'Video' },
    ])
    .execute();

  await trx
    .insertInto('resourceTags')
    .values([
      { resourceId: resourceId1, tagId: interviewPrepTagId },
      { resourceId: resourceId1, tagId: learningTagId },
      { resourceId: resourceId2, tagId: careerAdviceTagId },
      { resourceId: resourceId2, tagId: videoTagId },
      { resourceId: resourceId3, tagId: academicTagId },
      { resourceId: resourceId3, tagId: learningTagId },
    ])
    .execute();

  await trx
    .insertInto('resourceUpvotes')
    .values([
      { resourceId: resourceId1, studentId: memberId1 },
      { resourceId: resourceId1, studentId: memberId2 },
      { resourceId: resourceId1, studentId: memberId3 },
      { resourceId: resourceId2, studentId: memberId1 },
      { resourceId: resourceId2, studentId: memberId3 },
      { resourceId: resourceId3, studentId: memberId2 },
    ])
    .execute();

  // Slack Channels

  const slackChannelId1 = id();
  const slackChannelId2 = id();
  const slackChannelId3 = id();

  await trx
    .insertInto('slackChannels')
    .values([
      { id: slackChannelId1, name: 'announcements', type: 'public' },
      { id: slackChannelId2, name: 'general', type: 'public' },
      { id: slackChannelId3, name: 'random', type: 'public' },
    ])
    .execute();

  // Countries

  await trx
    .insertInto('countries')
    .values([
      {
        code: 'ABW',
        demonym: 'Aruban',
        flagEmoji: '🇦🇼',
        latitude: '12.5',
        longitude: '-69.96666666',
        name: 'Aruba',
        region: 'Americas',
        subregion: 'Caribbean',
      },
      {
        code: 'AFG',
        demonym: 'Afghan',
        flagEmoji: '🇦🇫',
        latitude: '33',
        longitude: '65',
        name: 'Afghanistan',
        region: 'Asia',
        subregion: 'Southern Asia',
      },
      {
        code: 'AGO',
        demonym: 'Angolan',
        flagEmoji: '🇦🇴',
        latitude: '-12.5',
        longitude: '18.5',
        name: 'Angola',
        region: 'Africa',
        subregion: 'Middle Africa',
      },
      {
        code: 'AIA',
        demonym: 'Anguillian',
        flagEmoji: '🇦🇮',
        latitude: '18.25',
        longitude: '-63.16666666',
        name: 'Anguilla',
        region: 'Americas',
        subregion: 'Caribbean',
      },
      {
        code: 'ALA',
        demonym: 'Ålandish',
        flagEmoji: '🇦🇽',
        latitude: '60.116667',
        longitude: '19.9',
        name: 'Åland Islands',
        region: 'Europe',
        subregion: 'Northern Europe',
      },
      {
        code: 'ALB',
        demonym: 'Albanian',
        flagEmoji: '🇦🇱',
        latitude: '41',
        longitude: '20',
        name: 'Albania',
        region: 'Europe',
        subregion: 'Southeast Europe',
      },
      {
        code: 'AND',
        demonym: 'Andorran',
        flagEmoji: '🇦🇩',
        latitude: '42.5',
        longitude: '1.5',
        name: 'Andorra',
        region: 'Europe',
        subregion: 'Southern Europe',
      },
      {
        code: 'ARE',
        demonym: 'Emirati',
        flagEmoji: '🇦🇪',
        latitude: '24',
        longitude: '54',
        name: 'United Arab Emirates',
        region: 'Asia',
        subregion: 'Western Asia',
      },
      {
        code: 'ARG',
        demonym: 'Argentine',
        flagEmoji: '🇦🇷',
        latitude: '-34',
        longitude: '-64',
        name: 'Argentina',
        region: 'Americas',
        subregion: 'South America',
      },
      {
        code: 'ARM',
        demonym: 'Armenian',
        flagEmoji: '🇦🇲',
        latitude: '40',
        longitude: '45',
        name: 'Armenia',
        region: 'Asia',
        subregion: 'Western Asia',
      },
      {
        code: 'ASM',
        demonym: 'American Samoan',
        flagEmoji: '🇦🇸',
        latitude: '-14.33333333',
        longitude: '-170',
        name: 'American Samoa',
        region: 'Oceania',
        subregion: 'Polynesia',
      },
      {
        code: 'ATA',
        demonym: 'Antarctican',
        flagEmoji: '🇦🇶',
        latitude: '-90',
        longitude: '0',
        name: 'Antarctica',
        region: 'Antarctic',
        subregion: null,
      },
      {
        code: 'ATF',
        demonym: 'French',
        flagEmoji: '🇹🇫',
        latitude: '-49.25',
        longitude: '69.167',
        name: 'French Southern and Antarctic Lands',
        region: 'Antarctic',
        subregion: null,
      },
      {
        code: 'ATG',
        demonym: 'Antiguan, Barbudan',
        flagEmoji: '🇦🇬',
        latitude: '17.05',
        longitude: '-61.8',
        name: 'Antigua and Barbuda',
        region: 'Americas',
        subregion: 'Caribbean',
      },
      {
        code: 'AUS',
        demonym: 'Australian',
        flagEmoji: '🇦🇺',
        latitude: '-27',
        longitude: '133',
        name: 'Australia',
        region: 'Oceania',
        subregion: 'Australia and New Zealand',
      },
      {
        code: 'AUT',
        demonym: 'Austrian',
        flagEmoji: '🇦🇹',
        latitude: '47.33333333',
        longitude: '13.33333333',
        name: 'Austria',
        region: 'Europe',
        subregion: 'Central Europe',
      },
      {
        code: 'AZE',
        demonym: 'Azerbaijani',
        flagEmoji: '🇦🇿',
        latitude: '40.5',
        longitude: '47.5',
        name: 'Azerbaijan',
        region: 'Asia',
        subregion: 'Western Asia',
      },
      {
        code: 'BDI',
        demonym: 'Burundian',
        flagEmoji: '🇧🇮',
        latitude: '-3.5',
        longitude: '30',
        name: 'Burundi',
        region: 'Africa',
        subregion: 'Eastern Africa',
      },
      {
        code: 'BEL',
        demonym: 'Belgian',
        flagEmoji: '🇧🇪',
        latitude: '50.83333333',
        longitude: '4',
        name: 'Belgium',
        region: 'Europe',
        subregion: 'Western Europe',
      },
      {
        code: 'BEN',
        demonym: 'Beninese',
        flagEmoji: '🇧🇯',
        latitude: '9.5',
        longitude: '2.25',
        name: 'Benin',
        region: 'Africa',
        subregion: 'Western Africa',
      },
      {
        code: 'BES',
        demonym: 'Dutch',
        flagEmoji: '🇧🇶',
        latitude: '12.18',
        longitude: '-68.25',
        name: 'Caribbean Netherlands',
        region: 'Americas',
        subregion: 'Caribbean',
      },
      {
        code: 'BFA',
        demonym: 'Burkinabe',
        flagEmoji: '🇧🇫',
        latitude: '13',
        longitude: '-2',
        name: 'Burkina Faso',
        region: 'Africa',
        subregion: 'Western Africa',
      },
      {
        code: 'BGD',
        demonym: 'Bangladeshi',
        flagEmoji: '🇧🇩',
        latitude: '24',
        longitude: '90',
        name: 'Bangladesh',
        region: 'Asia',
        subregion: 'Southern Asia',
      },
      {
        code: 'BGR',
        demonym: 'Bulgarian',
        flagEmoji: '🇧🇬',
        latitude: '43',
        longitude: '25',
        name: 'Bulgaria',
        region: 'Europe',
        subregion: 'Southeast Europe',
      },
      {
        code: 'BHR',
        demonym: 'Bahraini',
        flagEmoji: '🇧🇭',
        latitude: '26',
        longitude: '50.55',
        name: 'Bahrain',
        region: 'Asia',
        subregion: 'Western Asia',
      },
      {
        code: 'BHS',
        demonym: 'Bahamian',
        flagEmoji: '🇧🇸',
        latitude: '25.0343',
        longitude: '-77.3963',
        name: 'Bahamas',
        region: 'Americas',
        subregion: 'Caribbean',
      },
      {
        code: 'BIH',
        demonym: 'Bosnian, Herzegovinian',
        flagEmoji: '🇧🇦',
        latitude: '44',
        longitude: '18',
        name: 'Bosnia and Herzegovina',
        region: 'Europe',
        subregion: 'Southeast Europe',
      },
      {
        code: 'BLM',
        demonym: 'Saint Barthélemy Islander',
        flagEmoji: '🇧🇱',
        latitude: '18.5',
        longitude: '-63.41666666',
        name: 'Saint Barthélemy',
        region: 'Americas',
        subregion: 'Caribbean',
      },
      {
        code: 'BLR',
        demonym: 'Belarusian',
        flagEmoji: '🇧🇾',
        latitude: '53',
        longitude: '28',
        name: 'Belarus',
        region: 'Europe',
        subregion: 'Eastern Europe',
      },
      {
        code: 'BLZ',
        demonym: 'Belizean',
        flagEmoji: '🇧🇿',
        latitude: '17.25',
        longitude: '-88.75',
        name: 'Belize',
        region: 'Americas',
        subregion: 'Central America',
      },
      {
        code: 'BMU',
        demonym: 'Bermudian',
        flagEmoji: '🇧🇲',
        latitude: '32.33333333',
        longitude: '-64.75',
        name: 'Bermuda',
        region: 'Americas',
        subregion: 'North America',
      },
      {
        code: 'BOL',
        demonym: 'Bolivian',
        flagEmoji: '🇧🇴',
        latitude: '-17',
        longitude: '-65',
        name: 'Bolivia',
        region: 'Americas',
        subregion: 'South America',
      },
      {
        code: 'BRA',
        demonym: 'Brazilian',
        flagEmoji: '🇧🇷',
        latitude: '-10',
        longitude: '-55',
        name: 'Brazil',
        region: 'Americas',
        subregion: 'South America',
      },
      {
        code: 'BRB',
        demonym: 'Barbadian',
        flagEmoji: '🇧🇧',
        latitude: '13.16666666',
        longitude: '-59.53333333',
        name: 'Barbados',
        region: 'Americas',
        subregion: 'Caribbean',
      },
      {
        code: 'BRN',
        demonym: 'Bruneian',
        flagEmoji: '🇧🇳',
        latitude: '4.5',
        longitude: '114.66666666',
        name: 'Brunei',
        region: 'Asia',
        subregion: 'South-Eastern Asia',
      },
      {
        code: 'BTN',
        demonym: 'Bhutanese',
        flagEmoji: '🇧🇹',
        latitude: '27.5',
        longitude: '90.5',
        name: 'Bhutan',
        region: 'Asia',
        subregion: 'Southern Asia',
      },
      {
        code: 'BWA',
        demonym: 'Motswana',
        flagEmoji: '🇧🇼',
        latitude: '-22',
        longitude: '24',
        name: 'Botswana',
        region: 'Africa',
        subregion: 'Southern Africa',
      },
      {
        code: 'CAF',
        demonym: 'Central African',
        flagEmoji: '🇨🇫',
        latitude: '7',
        longitude: '21',
        name: 'Central African Republic',
        region: 'Africa',
        subregion: 'Middle Africa',
      },
      {
        code: 'CAN',
        demonym: 'Canadian',
        flagEmoji: '🇨🇦',
        latitude: '60',
        longitude: '-95',
        name: 'Canada',
        region: 'Americas',
        subregion: 'North America',
      },
      {
        code: 'CCK',
        demonym: 'Cocos Islander',
        flagEmoji: '🇨🇨',
        latitude: '12.1642',
        longitude: '96.871',
        name: 'Cocos (Keeling) Islands',
        region: 'Oceania',
        subregion: 'Australia and New Zealand',
      },
      {
        code: 'CHE',
        demonym: 'Swiss',
        flagEmoji: '🇨🇭',
        latitude: '47',
        longitude: '8',
        name: 'Switzerland',
        region: 'Europe',
        subregion: 'Western Europe',
      },
      {
        code: 'CHL',
        demonym: 'Chilean',
        flagEmoji: '🇨🇱',
        latitude: '-30',
        longitude: '-71',
        name: 'Chile',
        region: 'Americas',
        subregion: 'South America',
      },
      {
        code: 'CHN',
        demonym: 'Chinese',
        flagEmoji: '🇨🇳',
        latitude: '35',
        longitude: '105',
        name: 'China',
        region: 'Asia',
        subregion: 'Eastern Asia',
      },
      {
        code: 'CIV',
        demonym: 'Ivorian',
        flagEmoji: '🇨🇮',
        latitude: '8',
        longitude: '-5',
        name: 'Ivory Coast',
        region: 'Africa',
        subregion: 'Western Africa',
      },
      {
        code: 'CMR',
        demonym: 'Cameroonian',
        flagEmoji: '🇨🇲',
        latitude: '6',
        longitude: '12',
        name: 'Cameroon',
        region: 'Africa',
        subregion: 'Middle Africa',
      },
      {
        code: 'COD',
        demonym: 'Congolese',
        flagEmoji: '🇨🇩',
        latitude: '0',
        longitude: '25',
        name: 'DR Congo',
        region: 'Africa',
        subregion: 'Middle Africa',
      },
      {
        code: 'COG',
        demonym: 'Congolese',
        flagEmoji: '🇨🇬',
        latitude: '-1',
        longitude: '15',
        name: 'Republic of the Congo',
        region: 'Africa',
        subregion: 'Middle Africa',
      },
      {
        code: 'COK',
        demonym: 'Cook Islander',
        flagEmoji: '🇨🇰',
        latitude: '-21.23333333',
        longitude: '-159.76666666',
        name: 'Cook Islands',
        region: 'Oceania',
        subregion: 'Polynesia',
      },
      {
        code: 'COL',
        demonym: 'Colombian',
        flagEmoji: '🇨🇴',
        latitude: '4',
        longitude: '-72',
        name: 'Colombia',
        region: 'Americas',
        subregion: 'South America',
      },
      {
        code: 'COM',
        demonym: 'Comoran',
        flagEmoji: '🇰🇲',
        latitude: '-12.16666666',
        longitude: '44.25',
        name: 'Comoros',
        region: 'Africa',
        subregion: 'Eastern Africa',
      },
      {
        code: 'CPV',
        demonym: 'Cape Verdian',
        flagEmoji: '🇨🇻',
        latitude: '16.5388',
        longitude: '23.0418',
        name: 'Cape Verde',
        region: 'Africa',
        subregion: 'Western Africa',
      },
      {
        code: 'CRI',
        demonym: 'Costa Rican',
        flagEmoji: '🇨🇷',
        latitude: '10',
        longitude: '-84',
        name: 'Costa Rica',
        region: 'Americas',
        subregion: 'Central America',
      },
      {
        code: 'CUB',
        demonym: 'Cuban',
        flagEmoji: '🇨🇺',
        latitude: '21.5',
        longitude: '-80',
        name: 'Cuba',
        region: 'Americas',
        subregion: 'Caribbean',
      },
      {
        code: 'CUW',
        demonym: 'Curaçaoan',
        flagEmoji: '🇨🇼',
        latitude: '12.116667',
        longitude: '-68.933333',
        name: 'Curaçao',
        region: 'Americas',
        subregion: 'Caribbean',
      },
      {
        code: 'CXR',
        demonym: 'Christmas Islander',
        flagEmoji: '🇨🇽',
        latitude: '-10.5',
        longitude: '105.66666666',
        name: 'Christmas Island',
        region: 'Oceania',
        subregion: 'Australia and New Zealand',
      },
      {
        code: 'CYM',
        demonym: 'Caymanian',
        flagEmoji: '🇰🇾',
        latitude: '19.3133',
        longitude: '-81.2546',
        name: 'Cayman Islands',
        region: 'Americas',
        subregion: 'Caribbean',
      },
      {
        code: 'CYP',
        demonym: 'Cypriot',
        flagEmoji: '🇨🇾',
        latitude: '35',
        longitude: '33',
        name: 'Cyprus',
        region: 'Europe',
        subregion: 'Southern Europe',
      },
      {
        code: 'CZE',
        demonym: 'Czech',
        flagEmoji: '🇨🇿',
        latitude: '49.75',
        longitude: '15.5',
        name: 'Czechia',
        region: 'Europe',
        subregion: 'Central Europe',
      },
      {
        code: 'DEU',
        demonym: 'German',
        flagEmoji: '🇩🇪',
        latitude: '51',
        longitude: '9',
        name: 'Germany',
        region: 'Europe',
        subregion: 'Western Europe',
      },
      {
        code: 'DJI',
        demonym: 'Djibouti',
        flagEmoji: '🇩🇯',
        latitude: '11.5',
        longitude: '43',
        name: 'Djibouti',
        region: 'Africa',
        subregion: 'Eastern Africa',
      },
      {
        code: 'DMA',
        demonym: 'Dominican',
        flagEmoji: '🇩🇲',
        latitude: '15.41666666',
        longitude: '-61.33333333',
        name: 'Dominica',
        region: 'Americas',
        subregion: 'Caribbean',
      },
      {
        code: 'DNK',
        demonym: 'Danish',
        flagEmoji: '🇩🇰',
        latitude: '56',
        longitude: '10',
        name: 'Denmark',
        region: 'Europe',
        subregion: 'Northern Europe',
      },
      {
        code: 'DOM',
        demonym: 'Dominican',
        flagEmoji: '🇩🇴',
        latitude: '19',
        longitude: '-70.66666666',
        name: 'Dominican Republic',
        region: 'Americas',
        subregion: 'Caribbean',
      },
      {
        code: 'DZA',
        demonym: 'Algerian',
        flagEmoji: '🇩🇿',
        latitude: '28',
        longitude: '3',
        name: 'Algeria',
        region: 'Africa',
        subregion: 'Northern Africa',
      },
      {
        code: 'ECU',
        demonym: 'Ecuadorean',
        flagEmoji: '🇪🇨',
        latitude: '-2',
        longitude: '-77.5',
        name: 'Ecuador',
        region: 'Americas',
        subregion: 'South America',
      },
      {
        code: 'EGY',
        demonym: 'Egyptian',
        flagEmoji: '🇪🇬',
        latitude: '27',
        longitude: '30',
        name: 'Egypt',
        region: 'Africa',
        subregion: 'Northern Africa',
      },
      {
        code: 'ERI',
        demonym: 'Eritrean',
        flagEmoji: '🇪🇷',
        latitude: '15',
        longitude: '39',
        name: 'Eritrea',
        region: 'Africa',
        subregion: 'Eastern Africa',
      },
      {
        code: 'ESH',
        demonym: 'Sahrawi',
        flagEmoji: '🇪🇭',
        latitude: '24.5',
        longitude: '-13',
        name: 'Western Sahara',
        region: 'Africa',
        subregion: 'Northern Africa',
      },
      {
        code: 'ESP',
        demonym: 'Spanish',
        flagEmoji: '🇪🇸',
        latitude: '40',
        longitude: '-4',
        name: 'Spain',
        region: 'Europe',
        subregion: 'Southern Europe',
      },
      {
        code: 'EST',
        demonym: 'Estonian',
        flagEmoji: '🇪🇪',
        latitude: '59',
        longitude: '26',
        name: 'Estonia',
        region: 'Europe',
        subregion: 'Northern Europe',
      },
      {
        code: 'ETH',
        demonym: 'Ethiopian',
        flagEmoji: '🇪🇹',
        latitude: '8',
        longitude: '38',
        name: 'Ethiopia',
        region: 'Africa',
        subregion: 'Eastern Africa',
      },
      {
        code: 'FIN',
        demonym: 'Finnish',
        flagEmoji: '🇫🇮',
        latitude: '64',
        longitude: '26',
        name: 'Finland',
        region: 'Europe',
        subregion: 'Northern Europe',
      },
      {
        code: 'FJI',
        demonym: 'Fijian',
        flagEmoji: '🇫🇯',
        latitude: '17.7134',
        longitude: '178.065',
        name: 'Fiji',
        region: 'Oceania',
        subregion: 'Melanesia',
      },
      {
        code: 'FLK',
        demonym: 'Falkland Islander',
        flagEmoji: '🇫🇰',
        latitude: '-51.75',
        longitude: '-59',
        name: 'Falkland Islands',
        region: 'Americas',
        subregion: 'South America',
      },
      {
        code: 'FRA',
        demonym: 'French',
        flagEmoji: '🇫🇷',
        latitude: '46',
        longitude: '2',
        name: 'France',
        region: 'Europe',
        subregion: 'Western Europe',
      },
      {
        code: 'FRO',
        demonym: 'Faroese',
        flagEmoji: '🇫🇴',
        latitude: '62',
        longitude: '-7',
        name: 'Faroe Islands',
        region: 'Europe',
        subregion: 'Northern Europe',
      },
      {
        code: 'FSM',
        demonym: 'Micronesian',
        flagEmoji: '🇫🇲',
        latitude: '6.91666666',
        longitude: '158.25',
        name: 'Micronesia',
        region: 'Oceania',
        subregion: 'Micronesia',
      },
      {
        code: 'GAB',
        demonym: 'Gabonese',
        flagEmoji: '🇬🇦',
        latitude: '-1',
        longitude: '11.75',
        name: 'Gabon',
        region: 'Africa',
        subregion: 'Middle Africa',
      },
      {
        code: 'GBR',
        demonym: 'British',
        flagEmoji: '🇬🇧',
        latitude: '54',
        longitude: '-2',
        name: 'United Kingdom',
        region: 'Europe',
        subregion: 'Northern Europe',
      },
      {
        code: 'GEO',
        demonym: 'Georgian',
        flagEmoji: '🇬🇪',
        latitude: '42',
        longitude: '43.5',
        name: 'Georgia',
        region: 'Asia',
        subregion: 'Western Asia',
      },
      {
        code: 'GGY',
        demonym: 'Channel Islander',
        flagEmoji: '🇬🇬',
        latitude: '49.46666666',
        longitude: '-2.58333333',
        name: 'Guernsey',
        region: 'Europe',
        subregion: 'Northern Europe',
      },
      {
        code: 'GHA',
        demonym: 'Ghanaian',
        flagEmoji: '🇬🇭',
        latitude: '8',
        longitude: '-2',
        name: 'Ghana',
        region: 'Africa',
        subregion: 'Western Africa',
      },
      {
        code: 'GIB',
        demonym: 'Gibraltar',
        flagEmoji: '🇬🇮',
        latitude: '36.13333333',
        longitude: '-5.35',
        name: 'Gibraltar',
        region: 'Europe',
        subregion: 'Southern Europe',
      },
      {
        code: 'GIN',
        demonym: 'Guinean',
        flagEmoji: '🇬🇳',
        latitude: '11',
        longitude: '-10',
        name: 'Guinea',
        region: 'Africa',
        subregion: 'Western Africa',
      },
      {
        code: 'GLP',
        demonym: 'Guadeloupian',
        flagEmoji: '🇬🇵',
        latitude: '16.25',
        longitude: '-61.583333',
        name: 'Guadeloupe',
        region: 'Americas',
        subregion: 'Caribbean',
      },
      {
        code: 'GMB',
        demonym: 'Gambian',
        flagEmoji: '🇬🇲',
        latitude: '13.46666666',
        longitude: '-16.56666666',
        name: 'Gambia',
        region: 'Africa',
        subregion: 'Western Africa',
      },
      {
        code: 'GNB',
        demonym: 'Guinea-Bissauan',
        flagEmoji: '🇬🇼',
        latitude: '12',
        longitude: '-15',
        name: 'Guinea-Bissau',
        region: 'Africa',
        subregion: 'Western Africa',
      },
      {
        code: 'GNQ',
        demonym: 'Equatorial Guinean',
        flagEmoji: '🇬🇶',
        latitude: '2',
        longitude: '10',
        name: 'Equatorial Guinea',
        region: 'Africa',
        subregion: 'Middle Africa',
      },
      {
        code: 'GRC',
        demonym: 'Greek',
        flagEmoji: '🇬🇷',
        latitude: '39',
        longitude: '22',
        name: 'Greece',
        region: 'Europe',
        subregion: 'Southern Europe',
      },
      {
        code: 'GRD',
        demonym: 'Grenadian',
        flagEmoji: '🇬🇩',
        latitude: '12.11666666',
        longitude: '-61.66666666',
        name: 'Grenada',
        region: 'Americas',
        subregion: 'Caribbean',
      },
      {
        code: 'GRL',
        demonym: 'Greenlandic',
        flagEmoji: '🇬🇱',
        latitude: '72',
        longitude: '-40',
        name: 'Greenland',
        region: 'Americas',
        subregion: 'North America',
      },
      {
        code: 'GTM',
        demonym: 'Guatemalan',
        flagEmoji: '🇬🇹',
        latitude: '15.5',
        longitude: '-90.25',
        name: 'Guatemala',
        region: 'Americas',
        subregion: 'Central America',
      },
      {
        code: 'GUF',
        demonym: 'Guianan',
        flagEmoji: '🇬🇫',
        latitude: '4',
        longitude: '-53',
        name: 'French Guiana',
        region: 'Americas',
        subregion: 'South America',
      },
      {
        code: 'GUM',
        demonym: 'Guamanian',
        flagEmoji: '🇬🇺',
        latitude: '13.46666666',
        longitude: '144.78333333',
        name: 'Guam',
        region: 'Oceania',
        subregion: 'Micronesia',
      },
      {
        code: 'GUY',
        demonym: 'Guyanese',
        flagEmoji: '🇬🇾',
        latitude: '5',
        longitude: '-59',
        name: 'Guyana',
        region: 'Americas',
        subregion: 'South America',
      },
      {
        code: 'HKG',
        demonym: 'Hong Konger',
        flagEmoji: '🇭🇰',
        latitude: '22.267',
        longitude: '114.188',
        name: 'Hong Kong',
        region: 'Asia',
        subregion: 'Eastern Asia',
      },
      {
        code: 'HMD',
        demonym: 'Heard and McDonald Islander',
        flagEmoji: '🇭🇲',
        latitude: '53.0818',
        longitude: '73.5042',
        name: 'Heard Island and McDonald Islands',
        region: 'Antarctic',
        subregion: null,
      },
      {
        code: 'HND',
        demonym: 'Honduran',
        flagEmoji: '🇭🇳',
        latitude: '15',
        longitude: '-86.5',
        name: 'Honduras',
        region: 'Americas',
        subregion: 'Central America',
      },
      {
        code: 'HRV',
        demonym: 'Croatian',
        flagEmoji: '🇭🇷',
        latitude: '45.16666666',
        longitude: '15.5',
        name: 'Croatia',
        region: 'Europe',
        subregion: 'Southeast Europe',
      },
      {
        code: 'HTI',
        demonym: 'Haitian',
        flagEmoji: '🇭🇹',
        latitude: '19',
        longitude: '-72.41666666',
        name: 'Haiti',
        region: 'Americas',
        subregion: 'Caribbean',
      },
      {
        code: 'HUN',
        demonym: 'Hungarian',
        flagEmoji: '🇭🇺',
        latitude: '47',
        longitude: '20',
        name: 'Hungary',
        region: 'Europe',
        subregion: 'Central Europe',
      },
      {
        code: 'IDN',
        demonym: 'Indonesian',
        flagEmoji: '🇮🇩',
        latitude: '-5',
        longitude: '120',
        name: 'Indonesia',
        region: 'Asia',
        subregion: 'South-Eastern Asia',
      },
      {
        code: 'IMN',
        demonym: 'Manx',
        flagEmoji: '🇮🇲',
        latitude: '54.25',
        longitude: '-4.5',
        name: 'Isle of Man',
        region: 'Europe',
        subregion: 'Northern Europe',
      },
      {
        code: 'IND',
        demonym: 'Indian',
        flagEmoji: '🇮🇳',
        latitude: '20',
        longitude: '77',
        name: 'India',
        region: 'Asia',
        subregion: 'Southern Asia',
      },
      {
        code: 'IOT',
        demonym: 'Indian',
        flagEmoji: '🇮🇴',
        latitude: '-6',
        longitude: '71.5',
        name: 'British Indian Ocean Territory',
        region: 'Africa',
        subregion: 'Eastern Africa',
      },
      {
        code: 'IRL',
        demonym: 'Irish',
        flagEmoji: '🇮🇪',
        latitude: '53',
        longitude: '-8',
        name: 'Ireland',
        region: 'Europe',
        subregion: 'Northern Europe',
      },
      {
        code: 'IRN',
        demonym: 'Iranian',
        flagEmoji: '🇮🇷',
        latitude: '32',
        longitude: '53',
        name: 'Iran',
        region: 'Asia',
        subregion: 'Southern Asia',
      },
      {
        code: 'IRQ',
        demonym: 'Iraqi',
        flagEmoji: '🇮🇶',
        latitude: '33',
        longitude: '44',
        name: 'Iraq',
        region: 'Asia',
        subregion: 'Western Asia',
      },
      {
        code: 'ISL',
        demonym: 'Icelander',
        flagEmoji: '🇮🇸',
        latitude: '65',
        longitude: '-18',
        name: 'Iceland',
        region: 'Europe',
        subregion: 'Northern Europe',
      },
      {
        code: 'ISR',
        demonym: 'Israeli',
        flagEmoji: '🇮🇱',
        latitude: '31.47',
        longitude: '35.13',
        name: 'Israel',
        region: 'Asia',
        subregion: 'Western Asia',
      },
      {
        code: 'ITA',
        demonym: 'Italian',
        flagEmoji: '🇮🇹',
        latitude: '42.83333333',
        longitude: '12.83333333',
        name: 'Italy',
        region: 'Europe',
        subregion: 'Southern Europe',
      },
      {
        code: 'JAM',
        demonym: 'Jamaican',
        flagEmoji: '🇯🇲',
        latitude: '18.25',
        longitude: '-77.5',
        name: 'Jamaica',
        region: 'Americas',
        subregion: 'Caribbean',
      },
      {
        code: 'JEY',
        demonym: 'Channel Islander',
        flagEmoji: '🇯🇪',
        latitude: '49.25',
        longitude: '-2.16666666',
        name: 'Jersey',
        region: 'Europe',
        subregion: 'Northern Europe',
      },
      {
        code: 'JOR',
        demonym: 'Jordanian',
        flagEmoji: '🇯🇴',
        latitude: '31',
        longitude: '36',
        name: 'Jordan',
        region: 'Asia',
        subregion: 'Western Asia',
      },
      {
        code: 'JPN',
        demonym: 'Japanese',
        flagEmoji: '🇯🇵',
        latitude: '36',
        longitude: '138',
        name: 'Japan',
        region: 'Asia',
        subregion: 'Eastern Asia',
      },
      {
        code: 'KAZ',
        demonym: 'Kazakhstani',
        flagEmoji: '🇰🇿',
        latitude: '48.0196',
        longitude: '66.9237',
        name: 'Kazakhstan',
        region: 'Asia',
        subregion: 'Central Asia',
      },
      {
        code: 'KEN',
        demonym: 'Kenyan',
        flagEmoji: '🇰🇪',
        latitude: '1',
        longitude: '38',
        name: 'Kenya',
        region: 'Africa',
        subregion: 'Eastern Africa',
      },
      {
        code: 'KGZ',
        demonym: 'Kirghiz',
        flagEmoji: '🇰🇬',
        latitude: '41',
        longitude: '75',
        name: 'Kyrgyzstan',
        region: 'Asia',
        subregion: 'Central Asia',
      },
      {
        code: 'KHM',
        demonym: 'Cambodian',
        flagEmoji: '🇰🇭',
        latitude: '13',
        longitude: '105',
        name: 'Cambodia',
        region: 'Asia',
        subregion: 'South-Eastern Asia',
      },
      {
        code: 'KIR',
        demonym: 'I-Kiribati',
        flagEmoji: '🇰🇮',
        latitude: '1.41666666',
        longitude: '173',
        name: 'Kiribati',
        region: 'Oceania',
        subregion: 'Micronesia',
      },
      {
        code: 'KNA',
        demonym: 'Kittitian or Nevisian',
        flagEmoji: '🇰🇳',
        latitude: '17.33333333',
        longitude: '-62.75',
        name: 'Saint Kitts and Nevis',
        region: 'Americas',
        subregion: 'Caribbean',
      },
      {
        code: 'KOR',
        demonym: 'South Korean',
        flagEmoji: '🇰🇷',
        latitude: '37',
        longitude: '127.5',
        name: 'South Korea',
        region: 'Asia',
        subregion: 'Eastern Asia',
      },
      {
        code: 'KWT',
        demonym: 'Kuwaiti',
        flagEmoji: '🇰🇼',
        latitude: '29.5',
        longitude: '45.75',
        name: 'Kuwait',
        region: 'Asia',
        subregion: 'Western Asia',
      },
      {
        code: 'LAO',
        demonym: 'Laotian',
        flagEmoji: '🇱🇦',
        latitude: '18',
        longitude: '105',
        name: 'Laos',
        region: 'Asia',
        subregion: 'South-Eastern Asia',
      },
      {
        code: 'LBN',
        demonym: 'Lebanese',
        flagEmoji: '🇱🇧',
        latitude: '33.83333333',
        longitude: '35.83333333',
        name: 'Lebanon',
        region: 'Asia',
        subregion: 'Western Asia',
      },
      {
        code: 'LBR',
        demonym: 'Liberian',
        flagEmoji: '🇱🇷',
        latitude: '6.5',
        longitude: '-9.5',
        name: 'Liberia',
        region: 'Africa',
        subregion: 'Western Africa',
      },
      {
        code: 'LBY',
        demonym: 'Libyan',
        flagEmoji: '🇱🇾',
        latitude: '25',
        longitude: '17',
        name: 'Libya',
        region: 'Africa',
        subregion: 'Northern Africa',
      },
      {
        code: 'LCA',
        demonym: 'Saint Lucian',
        flagEmoji: '🇱🇨',
        latitude: '13.88333333',
        longitude: '-60.96666666',
        name: 'Saint Lucia',
        region: 'Americas',
        subregion: 'Caribbean',
      },
      {
        code: 'LIE',
        demonym: 'Liechtensteiner',
        flagEmoji: '🇱🇮',
        latitude: '47.26666666',
        longitude: '9.53333333',
        name: 'Liechtenstein',
        region: 'Europe',
        subregion: 'Western Europe',
      },
      {
        code: 'LKA',
        demonym: 'Sri Lankan',
        flagEmoji: '🇱🇰',
        latitude: '7',
        longitude: '81',
        name: 'Sri Lanka',
        region: 'Asia',
        subregion: 'Southern Asia',
      },
      {
        code: 'LSO',
        demonym: 'Mosotho',
        flagEmoji: '🇱🇸',
        latitude: '-29.5',
        longitude: '28.5',
        name: 'Lesotho',
        region: 'Africa',
        subregion: 'Southern Africa',
      },
      {
        code: 'LTU',
        demonym: 'Lithuanian',
        flagEmoji: '🇱🇹',
        latitude: '56',
        longitude: '24',
        name: 'Lithuania',
        region: 'Europe',
        subregion: 'Northern Europe',
      },
      {
        code: 'LUX',
        demonym: 'Luxembourger',
        flagEmoji: '🇱🇺',
        latitude: '49.75',
        longitude: '6.16666666',
        name: 'Luxembourg',
        region: 'Europe',
        subregion: 'Western Europe',
      },
      {
        code: 'LVA',
        demonym: 'Latvian',
        flagEmoji: '🇱🇻',
        latitude: '57',
        longitude: '25',
        name: 'Latvia',
        region: 'Europe',
        subregion: 'Northern Europe',
      },
      {
        code: 'MAC',
        demonym: 'Macanese',
        flagEmoji: '🇲🇴',
        latitude: '22.16666666',
        longitude: '113.55',
        name: 'Macau',
        region: 'Asia',
        subregion: 'Eastern Asia',
      },
      {
        code: 'MAF',
        demonym: 'Saint Martin Islander',
        flagEmoji: '🇲🇫',
        latitude: '18.0708',
        longitude: '63.0501',
        name: 'Saint Martin',
        region: 'Americas',
        subregion: 'Caribbean',
      },
      {
        code: 'MAR',
        demonym: 'Moroccan',
        flagEmoji: '🇲🇦',
        latitude: '32',
        longitude: '-5',
        name: 'Morocco',
        region: 'Africa',
        subregion: 'Northern Africa',
      },
      {
        code: 'MCO',
        demonym: 'Monegasque',
        flagEmoji: '🇲🇨',
        latitude: '43.73333333',
        longitude: '7.4',
        name: 'Monaco',
        region: 'Europe',
        subregion: 'Western Europe',
      },
      {
        code: 'MDA',
        demonym: 'Moldovan',
        flagEmoji: '🇲🇩',
        latitude: '47',
        longitude: '29',
        name: 'Moldova',
        region: 'Europe',
        subregion: 'Eastern Europe',
      },
      {
        code: 'MDG',
        demonym: 'Malagasy',
        flagEmoji: '🇲🇬',
        latitude: '-20',
        longitude: '47',
        name: 'Madagascar',
        region: 'Africa',
        subregion: 'Eastern Africa',
      },
      {
        code: 'MDV',
        demonym: 'Maldivan',
        flagEmoji: '🇲🇻',
        latitude: '3.25',
        longitude: '73',
        name: 'Maldives',
        region: 'Asia',
        subregion: 'Southern Asia',
      },
      {
        code: 'MEX',
        demonym: 'Mexican',
        flagEmoji: '🇲🇽',
        latitude: '23',
        longitude: '-102',
        name: 'Mexico',
        region: 'Americas',
        subregion: 'North America',
      },
      {
        code: 'MHL',
        demonym: 'Marshallese',
        flagEmoji: '🇲🇭',
        latitude: '9',
        longitude: '168',
        name: 'Marshall Islands',
        region: 'Oceania',
        subregion: 'Micronesia',
      },
      {
        code: 'MKD',
        demonym: 'Macedonian',
        flagEmoji: '🇲🇰',
        latitude: '41.83333333',
        longitude: '22',
        name: 'North Macedonia',
        region: 'Europe',
        subregion: 'Southeast Europe',
      },
      {
        code: 'MLI',
        demonym: 'Malian',
        flagEmoji: '🇲🇱',
        latitude: '17',
        longitude: '-4',
        name: 'Mali',
        region: 'Africa',
        subregion: 'Western Africa',
      },
      {
        code: 'MLT',
        demonym: 'Maltese',
        flagEmoji: '🇲🇹',
        latitude: '35.9375',
        longitude: '14.3754',
        name: 'Malta',
        region: 'Europe',
        subregion: 'Southern Europe',
      },
      {
        code: 'MMR',
        demonym: 'Burmese',
        flagEmoji: '🇲🇲',
        latitude: '22',
        longitude: '98',
        name: 'Myanmar',
        region: 'Asia',
        subregion: 'South-Eastern Asia',
      },
      {
        code: 'MNE',
        demonym: 'Montenegrin',
        flagEmoji: '🇲🇪',
        latitude: '42.5',
        longitude: '19.3',
        name: 'Montenegro',
        region: 'Europe',
        subregion: 'Southeast Europe',
      },
      {
        code: 'MNG',
        demonym: 'Mongolian',
        flagEmoji: '🇲🇳',
        latitude: '46',
        longitude: '105',
        name: 'Mongolia',
        region: 'Asia',
        subregion: 'Eastern Asia',
      },
      {
        code: 'MNP',
        demonym: 'American',
        flagEmoji: '🇲🇵',
        latitude: '15.2',
        longitude: '145.75',
        name: 'Northern Mariana Islands',
        region: 'Oceania',
        subregion: 'Micronesia',
      },
      {
        code: 'MOZ',
        demonym: 'Mozambican',
        flagEmoji: '🇲🇿',
        latitude: '-18.25',
        longitude: '35',
        name: 'Mozambique',
        region: 'Africa',
        subregion: 'Eastern Africa',
      },
      {
        code: 'MRT',
        demonym: 'Mauritanian',
        flagEmoji: '🇲🇷',
        latitude: '20',
        longitude: '-12',
        name: 'Mauritania',
        region: 'Africa',
        subregion: 'Western Africa',
      },
      {
        code: 'MSR',
        demonym: 'Montserratian',
        flagEmoji: '🇲🇸',
        latitude: '16.75',
        longitude: '-62.2',
        name: 'Montserrat',
        region: 'Americas',
        subregion: 'Caribbean',
      },
      {
        code: 'MTQ',
        demonym: 'Martinican',
        flagEmoji: '🇲🇶',
        latitude: '14.666667',
        longitude: '-61',
        name: 'Martinique',
        region: 'Americas',
        subregion: 'Caribbean',
      },
      {
        code: 'MUS',
        demonym: 'Mauritian',
        flagEmoji: '🇲🇺',
        latitude: '-20.28333333',
        longitude: '57.55',
        name: 'Mauritius',
        region: 'Africa',
        subregion: 'Eastern Africa',
      },
      {
        code: 'MWI',
        demonym: 'Malawian',
        flagEmoji: '🇲🇼',
        latitude: '-13.5',
        longitude: '34',
        name: 'Malawi',
        region: 'Africa',
        subregion: 'Eastern Africa',
      },
      {
        code: 'MYS',
        demonym: 'Malaysian',
        flagEmoji: '🇲🇾',
        latitude: '2.5',
        longitude: '112.5',
        name: 'Malaysia',
        region: 'Asia',
        subregion: 'South-Eastern Asia',
      },
      {
        code: 'MYT',
        demonym: 'Mahoran',
        flagEmoji: '🇾🇹',
        latitude: '-12.83333333',
        longitude: '45.16666666',
        name: 'Mayotte',
        region: 'Africa',
        subregion: 'Eastern Africa',
      },
      {
        code: 'NAM',
        demonym: 'Namibian',
        flagEmoji: '🇳🇦',
        latitude: '-22',
        longitude: '17',
        name: 'Namibia',
        region: 'Africa',
        subregion: 'Southern Africa',
      },
      {
        code: 'NCL',
        demonym: 'New Caledonian',
        flagEmoji: '🇳🇨',
        latitude: '-21.5',
        longitude: '165.5',
        name: 'New Caledonia',
        region: 'Oceania',
        subregion: 'Melanesia',
      },
      {
        code: 'NER',
        demonym: 'Nigerien',
        flagEmoji: '🇳🇪',
        latitude: '16',
        longitude: '8',
        name: 'Niger',
        region: 'Africa',
        subregion: 'Western Africa',
      },
      {
        code: 'NFK',
        demonym: 'Norfolk Islander',
        flagEmoji: '🇳🇫',
        latitude: '-29.03333333',
        longitude: '167.95',
        name: 'Norfolk Island',
        region: 'Oceania',
        subregion: 'Australia and New Zealand',
      },
      {
        code: 'NGA',
        demonym: 'Nigerian',
        flagEmoji: '🇳🇬',
        latitude: '10',
        longitude: '8',
        name: 'Nigeria',
        region: 'Africa',
        subregion: 'Western Africa',
      },
      {
        code: 'NIC',
        demonym: 'Nicaraguan',
        flagEmoji: '🇳🇮',
        latitude: '13',
        longitude: '-85',
        name: 'Nicaragua',
        region: 'Americas',
        subregion: 'Central America',
      },
      {
        code: 'NIU',
        demonym: 'Niuean',
        flagEmoji: '🇳🇺',
        latitude: '-19.03333333',
        longitude: '-169.86666666',
        name: 'Niue',
        region: 'Oceania',
        subregion: 'Polynesia',
      },
      {
        code: 'NLD',
        demonym: 'Dutch',
        flagEmoji: '🇳🇱',
        latitude: '52.5',
        longitude: '5.75',
        name: 'Netherlands',
        region: 'Europe',
        subregion: 'Western Europe',
      },
      {
        code: 'NOR',
        demonym: 'Norwegian',
        flagEmoji: '🇳🇴',
        latitude: '62',
        longitude: '10',
        name: 'Norway',
        region: 'Europe',
        subregion: 'Northern Europe',
      },
      {
        code: 'NPL',
        demonym: 'Nepalese',
        flagEmoji: '🇳🇵',
        latitude: '28',
        longitude: '84',
        name: 'Nepal',
        region: 'Asia',
        subregion: 'Southern Asia',
      },
      {
        code: 'NRU',
        demonym: 'Nauruan',
        flagEmoji: '🇳🇷',
        latitude: '-0.53333333',
        longitude: '166.91666666',
        name: 'Nauru',
        region: 'Oceania',
        subregion: 'Micronesia',
      },
      {
        code: 'NZL',
        demonym: 'New Zealander',
        flagEmoji: '🇳🇿',
        latitude: '-41',
        longitude: '174',
        name: 'New Zealand',
        region: 'Oceania',
        subregion: 'Australia and New Zealand',
      },
      {
        code: 'OMN',
        demonym: 'Omani',
        flagEmoji: '🇴🇲',
        latitude: '21',
        longitude: '57',
        name: 'Oman',
        region: 'Asia',
        subregion: 'Western Asia',
      },
      {
        code: 'PAK',
        demonym: 'Pakistani',
        flagEmoji: '🇵🇰',
        latitude: '30',
        longitude: '70',
        name: 'Pakistan',
        region: 'Asia',
        subregion: 'Southern Asia',
      },
      {
        code: 'PAN',
        demonym: 'Panamanian',
        flagEmoji: '🇵🇦',
        latitude: '9',
        longitude: '-80',
        name: 'Panama',
        region: 'Americas',
        subregion: 'Central America',
      },
      {
        code: 'PCN',
        demonym: 'Pitcairn Islander',
        flagEmoji: '🇵🇳',
        latitude: '-25.06666666',
        longitude: '-130.1',
        name: 'Pitcairn Islands',
        region: 'Oceania',
        subregion: 'Polynesia',
      },
      {
        code: 'PER',
        demonym: 'Peruvian',
        flagEmoji: '🇵🇪',
        latitude: '-10',
        longitude: '-76',
        name: 'Peru',
        region: 'Americas',
        subregion: 'South America',
      },
      {
        code: 'PHL',
        demonym: 'Filipino',
        flagEmoji: '🇵🇭',
        latitude: '13',
        longitude: '122',
        name: 'Philippines',
        region: 'Asia',
        subregion: 'South-Eastern Asia',
      },
      {
        code: 'PLW',
        demonym: 'Palauan',
        flagEmoji: '🇵🇼',
        latitude: '7.5',
        longitude: '134.5',
        name: 'Palau',
        region: 'Oceania',
        subregion: 'Micronesia',
      },
      {
        code: 'PNG',
        demonym: 'Papua New Guinean',
        flagEmoji: '🇵🇬',
        latitude: '-6',
        longitude: '147',
        name: 'Papua New Guinea',
        region: 'Oceania',
        subregion: 'Melanesia',
      },
      {
        code: 'POL',
        demonym: 'Polish',
        flagEmoji: '🇵🇱',
        latitude: '52',
        longitude: '20',
        name: 'Poland',
        region: 'Europe',
        subregion: 'Central Europe',
      },
      {
        code: 'PRI',
        demonym: 'Puerto Rican',
        flagEmoji: '🇵🇷',
        latitude: '18.25',
        longitude: '-66.5',
        name: 'Puerto Rico',
        region: 'Americas',
        subregion: 'Caribbean',
      },
      {
        code: 'PRK',
        demonym: 'North Korean',
        flagEmoji: '🇰🇵',
        latitude: '40',
        longitude: '127',
        name: 'North Korea',
        region: 'Asia',
        subregion: 'Eastern Asia',
      },
      {
        code: 'PRT',
        demonym: 'Portuguese',
        flagEmoji: '🇵🇹',
        latitude: '39.5',
        longitude: '-8',
        name: 'Portugal',
        region: 'Europe',
        subregion: 'Southern Europe',
      },
      {
        code: 'PRY',
        demonym: 'Paraguayan',
        flagEmoji: '🇵🇾',
        latitude: '-23',
        longitude: '-58',
        name: 'Paraguay',
        region: 'Americas',
        subregion: 'South America',
      },
      {
        code: 'PSE',
        demonym: 'Palestinian',
        flagEmoji: '🇵🇸',
        latitude: '31.9',
        longitude: '35.2',
        name: 'Palestine',
        region: 'Asia',
        subregion: 'Western Asia',
      },
      {
        code: 'PYF',
        demonym: 'French Polynesian',
        flagEmoji: '🇵🇫',
        latitude: '17.6797',
        longitude: '149.4068',
        name: 'French Polynesia',
        region: 'Oceania',
        subregion: 'Polynesia',
      },
      {
        code: 'QAT',
        demonym: 'Qatari',
        flagEmoji: '🇶🇦',
        latitude: '25.5',
        longitude: '51.25',
        name: 'Qatar',
        region: 'Asia',
        subregion: 'Western Asia',
      },
      {
        code: 'REU',
        demonym: 'Réunionese',
        flagEmoji: '🇷🇪',
        latitude: '-21.15',
        longitude: '55.5',
        name: 'Réunion',
        region: 'Africa',
        subregion: 'Eastern Africa',
      },
      {
        code: 'ROU',
        demonym: 'Romanian',
        flagEmoji: '🇷🇴',
        latitude: '46',
        longitude: '25',
        name: 'Romania',
        region: 'Europe',
        subregion: 'Southeast Europe',
      },
      {
        code: 'RUS',
        demonym: 'Russian',
        flagEmoji: '🇷🇺',
        latitude: '60',
        longitude: '100',
        name: 'Russia',
        region: 'Europe',
        subregion: 'Eastern Europe',
      },
      {
        code: 'RWA',
        demonym: 'Rwandan',
        flagEmoji: '🇷🇼',
        latitude: '-2',
        longitude: '30',
        name: 'Rwanda',
        region: 'Africa',
        subregion: 'Eastern Africa',
      },
      {
        code: 'SAU',
        demonym: 'Saudi Arabian',
        flagEmoji: '🇸🇦',
        latitude: '25',
        longitude: '45',
        name: 'Saudi Arabia',
        region: 'Asia',
        subregion: 'Western Asia',
      },
      {
        code: 'SDN',
        demonym: 'Sudanese',
        flagEmoji: '🇸🇩',
        latitude: '15',
        longitude: '30',
        name: 'Sudan',
        region: 'Africa',
        subregion: 'Northern Africa',
      },
      {
        code: 'SEN',
        demonym: 'Senegalese',
        flagEmoji: '🇸🇳',
        latitude: '14',
        longitude: '-14',
        name: 'Senegal',
        region: 'Africa',
        subregion: 'Western Africa',
      },
      {
        code: 'SGP',
        demonym: 'Singaporean',
        flagEmoji: '🇸🇬',
        latitude: '1.36666666',
        longitude: '103.8',
        name: 'Singapore',
        region: 'Asia',
        subregion: 'South-Eastern Asia',
      },
      {
        code: 'SGS',
        demonym: 'South Georgian South Sandwich Islander',
        flagEmoji: '🇬🇸',
        latitude: '-54.5',
        longitude: '-37',
        name: 'South Georgia',
        region: 'Antarctic',
        subregion: null,
      },
      {
        code: 'SHN',
        demonym: 'Saint Helenian',
        flagEmoji: '🇸🇭',
        latitude: '-15.95',
        longitude: '-5.72',
        name: 'Saint Helena, Ascension and Tristan da Cunha',
        region: 'Africa',
        subregion: 'Western Africa',
      },
      {
        code: 'SJM',
        demonym: 'Norwegian',
        flagEmoji: '🇸🇯',
        latitude: '78',
        longitude: '20',
        name: 'Svalbard and Jan Mayen',
        region: 'Europe',
        subregion: 'Northern Europe',
      },
      {
        code: 'SLB',
        demonym: 'Solomon Islander',
        flagEmoji: '🇸🇧',
        latitude: '-8',
        longitude: '159',
        name: 'Solomon Islands',
        region: 'Oceania',
        subregion: 'Melanesia',
      },
      {
        code: 'SLE',
        demonym: 'Sierra Leonean',
        flagEmoji: '🇸🇱',
        latitude: '8.5',
        longitude: '-11.5',
        name: 'Sierra Leone',
        region: 'Africa',
        subregion: 'Western Africa',
      },
      {
        code: 'SLV',
        demonym: 'Salvadoran',
        flagEmoji: '🇸🇻',
        latitude: '13.83333333',
        longitude: '-88.91666666',
        name: 'El Salvador',
        region: 'Americas',
        subregion: 'Central America',
      },
      {
        code: 'SMR',
        demonym: 'Sammarinese',
        flagEmoji: '🇸🇲',
        latitude: '43.76666666',
        longitude: '12.41666666',
        name: 'San Marino',
        region: 'Europe',
        subregion: 'Southern Europe',
      },
      {
        code: 'SOM',
        demonym: 'Somali',
        flagEmoji: '🇸🇴',
        latitude: '10',
        longitude: '49',
        name: 'Somalia',
        region: 'Africa',
        subregion: 'Eastern Africa',
      },
      {
        code: 'SPM',
        demonym: 'Saint-Pierrais, Miquelonnais',
        flagEmoji: '🇵🇲',
        latitude: '46.83333333',
        longitude: '-56.33333333',
        name: 'Saint Pierre and Miquelon',
        region: 'Americas',
        subregion: 'North America',
      },
      {
        code: 'SRB',
        demonym: 'Serbian',
        flagEmoji: '🇷🇸',
        latitude: '44',
        longitude: '21',
        name: 'Serbia',
        region: 'Europe',
        subregion: 'Southeast Europe',
      },
      {
        code: 'SSD',
        demonym: 'South Sudanese',
        flagEmoji: '🇸🇸',
        latitude: '7',
        longitude: '30',
        name: 'South Sudan',
        region: 'Africa',
        subregion: 'Middle Africa',
      },
      {
        code: 'STP',
        demonym: 'Sao Tomean',
        flagEmoji: '🇸🇹',
        latitude: '1',
        longitude: '7',
        name: 'São Tomé and Príncipe',
        region: 'Africa',
        subregion: 'Middle Africa',
      },
      {
        code: 'SUR',
        demonym: 'Surinamer',
        flagEmoji: '🇸🇷',
        latitude: '4',
        longitude: '-56',
        name: 'Suriname',
        region: 'Americas',
        subregion: 'South America',
      },
      {
        code: 'SVK',
        demonym: 'Slovak',
        flagEmoji: '🇸🇰',
        latitude: '48.66666666',
        longitude: '19.5',
        name: 'Slovakia',
        region: 'Europe',
        subregion: 'Central Europe',
      },
      {
        code: 'SVN',
        demonym: 'Slovene',
        flagEmoji: '🇸🇮',
        latitude: '46.11666666',
        longitude: '14.81666666',
        name: 'Slovenia',
        region: 'Europe',
        subregion: 'Central Europe',
      },
      {
        code: 'SWE',
        demonym: 'Swedish',
        flagEmoji: '🇸🇪',
        latitude: '62',
        longitude: '15',
        name: 'Sweden',
        region: 'Europe',
        subregion: 'Northern Europe',
      },
      {
        code: 'SWZ',
        demonym: 'Swazi',
        flagEmoji: '🇸🇿',
        latitude: '-26.5',
        longitude: '31.5',
        name: 'Eswatini',
        region: 'Africa',
        subregion: 'Southern Africa',
      },
      {
        code: 'SXM',
        demonym: 'St. Maartener',
        flagEmoji: '🇸🇽',
        latitude: '18.033333',
        longitude: '-63.05',
        name: 'Sint Maarten',
        region: 'Americas',
        subregion: 'Caribbean',
      },
      {
        code: 'SYC',
        demonym: 'Seychellois',
        flagEmoji: '🇸🇨',
        latitude: '-4.58333333',
        longitude: '55.66666666',
        name: 'Seychelles',
        region: 'Africa',
        subregion: 'Eastern Africa',
      },
      {
        code: 'SYR',
        demonym: 'Syrian',
        flagEmoji: '🇸🇾',
        latitude: '35',
        longitude: '38',
        name: 'Syria',
        region: 'Asia',
        subregion: 'Western Asia',
      },
      {
        code: 'TCA',
        demonym: 'Turks and Caicos Islander',
        flagEmoji: '🇹🇨',
        latitude: '21.75',
        longitude: '-71.58333333',
        name: 'Turks and Caicos Islands',
        region: 'Americas',
        subregion: 'Caribbean',
      },
      {
        code: 'TCD',
        demonym: 'Chadian',
        flagEmoji: '🇹🇩',
        latitude: '15',
        longitude: '19',
        name: 'Chad',
        region: 'Africa',
        subregion: 'Middle Africa',
      },
      {
        code: 'TGO',
        demonym: 'Togolese',
        flagEmoji: '🇹🇬',
        latitude: '8',
        longitude: '1.16666666',
        name: 'Togo',
        region: 'Africa',
        subregion: 'Western Africa',
      },
      {
        code: 'THA',
        demonym: 'Thai',
        flagEmoji: '🇹🇭',
        latitude: '15',
        longitude: '100',
        name: 'Thailand',
        region: 'Asia',
        subregion: 'South-Eastern Asia',
      },
      {
        code: 'TJK',
        demonym: 'Tadzhik',
        flagEmoji: '🇹🇯',
        latitude: '39',
        longitude: '71',
        name: 'Tajikistan',
        region: 'Asia',
        subregion: 'Central Asia',
      },
      {
        code: 'TKL',
        demonym: 'Tokelauan',
        flagEmoji: '🇹🇰',
        latitude: '-9',
        longitude: '-172',
        name: 'Tokelau',
        region: 'Oceania',
        subregion: 'Polynesia',
      },
      {
        code: 'TKM',
        demonym: 'Turkmen',
        flagEmoji: '🇹🇲',
        latitude: '40',
        longitude: '60',
        name: 'Turkmenistan',
        region: 'Asia',
        subregion: 'Central Asia',
      },
      {
        code: 'TLS',
        demonym: 'East Timorese',
        flagEmoji: '🇹🇱',
        latitude: '-8.83333333',
        longitude: '125.91666666',
        name: 'Timor-Leste',
        region: 'Asia',
        subregion: 'South-Eastern Asia',
      },
      {
        code: 'TON',
        demonym: 'Tongan',
        flagEmoji: '🇹🇴',
        latitude: '-20',
        longitude: '-175',
        name: 'Tonga',
        region: 'Oceania',
        subregion: 'Polynesia',
      },
      {
        code: 'TTO',
        demonym: 'Trinidadian',
        flagEmoji: '🇹🇹',
        latitude: '10.6918',
        longitude: '-61.2225',
        name: 'Trinidad and Tobago',
        region: 'Americas',
        subregion: 'Caribbean',
      },
      {
        code: 'TUN',
        demonym: 'Tunisian',
        flagEmoji: '🇹🇳',
        latitude: '34',
        longitude: '9',
        name: 'Tunisia',
        region: 'Africa',
        subregion: 'Northern Africa',
      },
      {
        code: 'TUR',
        demonym: 'Turkish',
        flagEmoji: '🇹🇷',
        latitude: '39',
        longitude: '35',
        name: 'Turkey',
        region: 'Asia',
        subregion: 'Western Asia',
      },
      {
        code: 'TUV',
        demonym: 'Tuvaluan',
        flagEmoji: '🇹🇻',
        latitude: '-8',
        longitude: '178',
        name: 'Tuvalu',
        region: 'Oceania',
        subregion: 'Polynesia',
      },
      {
        code: 'TWN',
        demonym: 'Taiwanese',
        flagEmoji: '🇹🇼',
        latitude: '23.5',
        longitude: '121',
        name: 'Taiwan',
        region: 'Asia',
        subregion: 'Eastern Asia',
      },
      {
        code: 'TZA',
        demonym: 'Tanzanian',
        flagEmoji: '🇹🇿',
        latitude: '-6',
        longitude: '35',
        name: 'Tanzania',
        region: 'Africa',
        subregion: 'Eastern Africa',
      },
      {
        code: 'UGA',
        demonym: 'Ugandan',
        flagEmoji: '🇺🇬',
        latitude: '1',
        longitude: '32',
        name: 'Uganda',
        region: 'Africa',
        subregion: 'Eastern Africa',
      },
      {
        code: 'UKR',
        demonym: 'Ukrainian',
        flagEmoji: '🇺🇦',
        latitude: '49',
        longitude: '32',
        name: 'Ukraine',
        region: 'Europe',
        subregion: 'Eastern Europe',
      },
      {
        code: 'UMI',
        demonym: 'American Islander',
        flagEmoji: '🇺🇲',
        latitude: '19.3',
        longitude: '166.633333',
        name: 'United States Minor Outlying Islands',
        region: 'Americas',
        subregion: 'North America',
      },
      {
        code: 'UNK',
        demonym: 'Kosovar',
        flagEmoji: '🇽🇰',
        latitude: '42.666667',
        longitude: '21.166667',
        name: 'Kosovo',
        region: 'Europe',
        subregion: 'Southeast Europe',
      },
      {
        code: 'URY',
        demonym: 'Uruguayan',
        flagEmoji: '🇺🇾',
        latitude: '-33',
        longitude: '-56',
        name: 'Uruguay',
        region: 'Americas',
        subregion: 'South America',
      },
      {
        code: 'USA',
        demonym: 'American',
        flagEmoji: '🇺🇸',
        latitude: '38',
        longitude: '-97',
        name: 'United States',
        region: 'Americas',
        subregion: 'North America',
      },
      {
        code: 'UZB',
        demonym: 'Uzbekistani',
        flagEmoji: '🇺🇿',
        latitude: '41',
        longitude: '64',
        name: 'Uzbekistan',
        region: 'Asia',
        subregion: 'Central Asia',
      },
      {
        code: 'VAT',
        demonym: 'Vatican',
        flagEmoji: '🇻🇦',
        latitude: '41.9',
        longitude: '12.45',
        name: 'Vatican City',
        region: 'Europe',
        subregion: 'Southern Europe',
      },
      {
        code: 'VCT',
        demonym: 'Saint Vincentian',
        flagEmoji: '🇻🇨',
        latitude: '13.25',
        longitude: '-61.2',
        name: 'Saint Vincent and the Grenadines',
        region: 'Americas',
        subregion: 'Caribbean',
      },
      {
        code: 'VEN',
        demonym: 'Venezuelan',
        flagEmoji: '🇻🇪',
        latitude: '8',
        longitude: '-66',
        name: 'Venezuela',
        region: 'Americas',
        subregion: 'South America',
      },
      {
        code: 'VGB',
        demonym: 'Virgin Islander',
        flagEmoji: '🇻🇬',
        latitude: '18.431383',
        longitude: '-64.62305',
        name: 'British Virgin Islands',
        region: 'Americas',
        subregion: 'Caribbean',
      },
      {
        code: 'VIR',
        demonym: 'Virgin Islander',
        flagEmoji: '🇻🇮',
        latitude: '18.35',
        longitude: '-64.933333',
        name: 'United States Virgin Islands',
        region: 'Americas',
        subregion: 'Caribbean',
      },
      {
        code: 'VNM',
        demonym: 'Vietnamese',
        flagEmoji: '🇻🇳',
        latitude: '16.16666666',
        longitude: '107.83333333',
        name: 'Vietnam',
        region: 'Asia',
        subregion: 'South-Eastern Asia',
      },
      {
        code: 'VUT',
        demonym: 'Ni-Vanuatu',
        flagEmoji: '🇻🇺',
        latitude: '-16',
        longitude: '167',
        name: 'Vanuatu',
        region: 'Oceania',
        subregion: 'Melanesia',
      },
      {
        code: 'WLF',
        demonym: 'Wallis and Futuna Islander',
        flagEmoji: '🇼🇫',
        latitude: '-13.3',
        longitude: '-176.2',
        name: 'Wallis and Futuna',
        region: 'Oceania',
        subregion: 'Polynesia',
      },
      {
        code: 'WSM',
        demonym: 'Samoan',
        flagEmoji: '🇼🇸',
        latitude: '-13.58333333',
        longitude: '-172.33333333',
        name: 'Samoa',
        region: 'Oceania',
        subregion: 'Polynesia',
      },
      {
        code: 'YEM',
        demonym: 'Yemeni',
        flagEmoji: '🇾🇪',
        latitude: '15',
        longitude: '48',
        name: 'Yemen',
        region: 'Asia',
        subregion: 'Western Asia',
      },
      {
        code: 'ZAF',
        demonym: 'South African',
        flagEmoji: '🇿🇦',
        latitude: '-29',
        longitude: '24',
        name: 'South Africa',
        region: 'Africa',
        subregion: 'Southern Africa',
      },
      {
        code: 'ZMB',
        demonym: 'Zambian',
        flagEmoji: '🇿🇲',
        latitude: '-15',
        longitude: '30',
        name: 'Zambia',
        region: 'Africa',
        subregion: 'Eastern Africa',
      },
      {
        code: 'ZWE',
        demonym: 'Zimbabwean',
        flagEmoji: '🇿🇼',
        latitude: '-20',
        longitude: '30',
        name: 'Zimbabwe',
        region: 'Africa',
        subregion: 'Southern Africa',
      },
    ])
    .execute();
}

main();
